### ISSUE TITLE
빌드 시 JWT 관련 프로퍼티 값 인식 못하는 오류 수정

### ISSUE THREAD

**Issue by oownahcohc** [Earth-Breakers/namu-backend#22]
## 문제 상황

```
java.lang.IllegalArgumentException:
 Could not resolve placeholder 'JWT_SECRET_KEY' in value "${JWT_SECRET_KEY}"
```
으로 인해 contextLoads 에 실패하며 build 에 실패합니다.

위와 같은 문제로, asciidoc 에 대한 html 파일도 생성하지 못하는 문제가 함께 발생합니다.

### 현재 token.yml

```yml
token:
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-valid-duration: ${JWT_ACCESS_VALID_DURATION}
    refresh-valid-duration: ${JWT_REFRESH_VALID_DURATION}
```
